# Generated by Django 5.2.6 on 2026-07-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Specific skills needed'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
