# Generated by Django 5.2.6 on 2026-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('MANAGER', 'NGO Manager'), ('CLIENT', 'Employer'), ('WORKER', 'Employee')], default='WORKER', max_length=20),
        ),
    ]
