# Generated by Django 5.2.6 on 2026-07-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_jobrequirement_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills, e.g. Carpentry, Masonry')),
                ('experience_years', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('daily_wage_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='client.jobrequirement')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='worker.workerprofile')),
            ],
        ),
    ]
